### ISSUE TITLE
saving downloads

### ISSUE THREAD

**Issue by hwhelchel** [jormon/minimal-chrome-on-heroku#2]
Has anyone used chrome to save downloads temporarily to heroku's filesystem? Wouldn't want to store them long term but send them to S3 or another storage service.

Here's what I have

```ruby
  def new_browser
    options = Selenium::WebDriver::Chrome::Options.new

    # make a directory for chrome if it doesn't already exist
    chrome_dir = File.join Dir.pwd, %w(tmp chrome)
    FileUtils.mkdir_p chrome_dir
    user_data_dir = "--user-data-dir=#{chrome_dir}"
    # add the option for user-data-dir
    options.add_argument user_data_dir

    # let Selenium know where to look for chrome if we have a hint from
    # heroku. chromedriver-helper & chrome seem to work out of the box on osx,
    # but not on heroku.
    if chrome_bin = ENV["GOOGLE_CHROME_BIN"]
      options.add_argument "no-sandbox"
      options.binary = chrome_bin
      # give a hint to here too
      Selenium::WebDriver::Chrome.driver_path = \
        "/app/vendor/bundle/bin/chromedriver"
    end

    # headless!
    options.add_argument "window-size=1200x600"
    options.add_argument "headless"
    options.add_argument "disable-gpu"

    # make the browser
    browser = Watir::Browser.new :chrome, options: options
    bridge = browser.driver.send(:bridge)
    path = '/session/:session_id/chromium/send_command'
    path[':session_id'] = bridge.session_id

    downloads_dir = File.join Dir.pwd, %w(tmp downloads)
    bridge.http.call(:post, path, cmd: 'Page.setDownloadBehavior',
                                  params: {
                                    behavior: 'allow',
                                    downloadPath: "#{Dir.pwd}/tmp"
                                  })
    browser
end
```
It is working locally but not on Heroku.

**Comment by jormon** [comment]
A few thoughts: (a) you create this `downloads_dir` variable but you don't use it in the `bridge.http.call` params. (b) you never `mkdir_p` the `tmp/downloads` folder, (like is done for the `tmp/chrome` folder) so it probably doesn't exist on Heroku.  Try `rm`ing that dir locally and see if it fails the same way it does on Heroku.

**Comment by hwhelchel** [comment]
@jormon thanks will try this today

**Comment by hwhelchel** [comment]
Hmm no dice yet.

So I tried it on Heroku. Saw the downloads folder created but the file didn't save.

<img width="672" alt="screen shot 2018-08-24 at 11 20 29 am" src="https://user-images.githubusercontent.com/4792375/44593369-28b75480-a791-11e8-8bc9-99909b070fd5.png">

Tried it locally. Same issue. The downloads folder was created and the file wasn't saved. 

<img width="408" alt="screen shot 2018-08-24 at 11 32 27 am" src="https://user-images.githubusercontent.com/4792375/44593478-716f0d80-a791-11e8-9d35-a00bdef51cf2.png">

Tried it locally--but not headless. I can see the file download start then Chrome crashes with a `EXC_BAD_ACCESS` error.

**Comment by hwhelchel** [comment]
Interesting so I commented out

```ruby
    bridge = browser.driver.send(:bridge)
    path = '/session/:session_id/chromium/send_command'
    path[':session_id'] = bridge.session_id

    downloads_dir = File.join Dir.pwd, %w(tmp downloads)
    FileUtils.mkdir_p downloads_dir
    bridge.http.call(:post, path, cmd: 'Page.setDownloadBehavior',
                                  params: {
                                    behavior: 'allow',
                                    downloadPath: downloads_dir
                                  })
```

and ran it non headless (head mode? 🤔) and it successfully downloaded the file to my `~/Downloads` folder.

Could it be a permissions issue on the new downloads folder I'm creating?

Created an issue on chromium with full stack trace: https://bugs.chromium.org/p/chromium/issues/detail?id=877516

**Comment by jormon** [comment]
hey @hwhelchel, check out #5 -- works for me on heroku-16.  don't hesitate to re-open if you have more issues.
